docs/examples/hello_world.md
docs/user_guide.md

Using Music Nerd as an introductory example.

Simpler example to start User Guide

---

README.md

Add instructions for sourcing a venv in Windows OS

UN-3066 Add instructions for sourcing a venv in Windows OS

---

.env.example
requirements.txt
run.py

Implement usage of .env file to run the app.
Changes:
- Add a .`env.example` to show how to add a .env file for the project
- Add pypi based dependencies to `requirements.txt`

UN-3063 Implement usage of .env file to run the app

---

coded_tools/music_nerd_pro_sly/accounting.py
coded_tools/music_nerd_pro_sly_local/accounting.py
docs/examples.md
docs/examples/music_nerd.md
docs/examples/music_nerd_pro.md
docs/examples/music_nerd_pro_local.md
docs/examples/music_nerd_pro_sly.md
docs/examples/music_nerd_pro_sly_local.md
registries/manifest.hocon
registries/music_nerd_pro_sly.hocon
registries/music_nerd_pro_sly_local.hocon

Added a simple example of how to manage a state using sly_data.

Sly data examples

---

README.md
docs/tutorial.md

Added links to:
- neuro-san-web-client
- nsflow
And updated `tutorial.md` to remove references to wheels_private.

Add links to UIs and remove refs to wheels_private

---

coded_tools/agentic_rag/rag.py
coded_tools/agentic_rag/slack.py
docs/examples.md
docs/examples/agentic_rag.md
registries/agentic_rag.hocon
registries/manifest.hocon
requirements.txt

- Add agentic_rag.hocon and `RAG` and `slack` tools
- Add pypdf in requirements.txt since it is actually the newer version
- Add md files

Agentic rag agent network

---

docs/examples/agentic_rag.md

and add link to langchain doc.

Add more info on bing search in md file

---

.env.example
README.md
requirements.txt

Couple of changes:
- Use `nsflow-0.5.9`
- Update `REAMDE.md` to install nsflow
- Update a couple of instructions in `REAMDE.md` for windows users

Use the latest nsflow

---

docs/tutorial.md

- Modify section **7** in `tutorial.md`.

Modify Tools section in tutorial

---

.env.example
coded_tools/intranet_agents_with_tools/absence_manager.py
coded_tools/intranet_agents_with_tools/check_leave_balances_tool.py
coded_tools/intranet_agents_with_tools/schedule_leave_tool.py
coded_tools/intranet_agents_with_tools/url_provider.py
docs/examples.md
docs/examples/agent_network_designer.md
docs/examples/intranet_agents.md
docs/examples/intranet_agents_with_tools.md
registries/intranet_agents_with_tools.hocon
registries/manifest.hocon

- Rename 1c to intranet_agents_with_tools
- Take Cognizant specific URLs out of the source code and read them to env variables instead
- Add new entry to doc/examples.md for the new demo (and for the old one, the intranet_agents)

UN 3068 move 1c demo to neuro-san-demos

---

tests/coded_tools/music_nerd_pro/test_accounting.py

Fixed the music_nerd_pro tests after the update to make the running cost less easy to guess for LLMs

Fix music_nerd_pro tests

---

docs/user_guide.md

- Add import and substitution section in `user_guide.md`

Substitution in hocon

---

.github/workflows/tests.yml

This PR provides a tests.yml to run the make lint, make lint-tests and make tests commands as well as some other checks. You can see the output of the current state here:
https://github.com/leaf-ai/neuro-san-demos/actions/runs/14848292939/job/41686894736
You'll see that the code is not rated 10/10 but the tests are still passing. I suppose there's a config somewhere to enforce 10/10.

Run ci/cd tests at each branch push and merge to main

---

coded_tools/agent_network_designer/get_agent_network_hocon.py

Fixed the loop over agents in Agent Network Designer's tool that was broken by the clean up done in https://github.com/leaf-ai/neuro-san-demos/pull/79

Fix get_agent_network_hocon.py loops over agents

---

registries/aaosa.hocon

This is so we can have an example that include this hocon file.

Add aaosa.hocon in registries

---

docs/tutorial.md

- Update table of content in tutorial  to reflect the changes in the tool section

Update table of content in tutorial 

---

coded_tools/agentic_rag/rag.py
coded_tools/agentic_rag/slack.py
registries/agentic_rag.hocon

fix flake8 and delete useless comments.

Tidy rag and slack tools

---

.env.example
coded_tools/agentforce/agentforce_adapter.py
docs/examples.md
docs/examples/agentforce.md
tests/coded_tools/agentforce/test_agentforce_adapter.py

Added documentation for the Agentforce agent network and how to configure it.
Also added a unittest to test connection to a live Agentforce agent.

Document the Agentforce agent network and coded tool

---

docs/user_guide.md

Updated the user guide to link to the neuro-san reference docs.

Update user guide to reference the neuro-san docs

---

coded_tools/agentic_rag/rag.py
coded_tools/agentic_rag/slack.py
requirements.txt
run.py

Changes:
- Fail aast on port conflict for `python -m run`
- Use nsflow latest version 0.5.11

Fail Fast on port conflict and add nsflow latest

---

docs/user_guide.md

Add link to A2A and CrewAI integration example in user guide

Add link to A2A and CrewAI integration example in user guide

---

.env.example
coded_tools/agentspace_adapter/agentspace_adapter.py
docs/examples.md
docs/examples/agentspace_adapter.md
docs/user_guide.md
registries/agentspace_adapter.hocon
registries/manifest.hocon

Add Agentspace example:
- Add agentspace_adapter.hocon to registries
- Add agentspace_adapter coded tool
- Add documentation around the example

Add Agentspace example

---

coded_tools/pdf_rag/pdf_rag.py
docs/examples.md
docs/examples/pdf_rag.md
registries/manifest.hocon
registries/pdf_rag.hocon
requirements.txt

- Add `pdf_rag.hocon` and its coded tool, `pdf_rag.py`.
- Add a md file.
- Add `pymupdf` in `requirements.txt`

PDF RAG Agent Network

---

registries/airline_policy.hocon
registries/pdf_rag.hocon
registries/smart_home.hocon
registries/smart_home_include.hocon

This PR cleans up old name references in the registries directory. This does not represent a full cleansing throughout the repo.

Update refs to leaf-ai and neuro-san-demos in registries directory

---

requirements.txt
run.py

Changes:
- Use latest nsflow
- Typo in run.py

Use latest nsflow

---

README.md

Added a short description to the blog posts in the README.

Add description for blog posts in README.md

---

requirements.txt

Upgrade neuro-san to 0.5.28 and neuro-san-web-client to 0.1.12

Upgrade neuro-san to 0.5.28 and neuro-san-web-client to 0.1.12

---

README.md

Changed the Conscious Agent icon in the README instead of reusing the A2A agent one.

Change Conscious Agent icon in README

---

Makefile
apps/conscious_assistant/conscious_assistant.py
apps/conscious_assistant/interface_flask.py
docs/examples/conscious_agent.md
pyproject.toml

Fixed some pylint and flake8 issues.

Pylint issues fixed

---

requirements.txt

Upgrade neuro-san to 0.5.29

---

requirements.txt

Upgrade to neuro-san 0.5.30

---

registries/intranet_agents_with_tools.hocon

Importing `aaosa.hocon` instructions in `Intranet_agent_with_tools.hocon` to:
- reuse standard instructions
- simplify the hocon file

Intranet_agent_with_tools: import aaosa.hocon

---

requirements.txt

Upgrade neuro-san to 0.5.31

---

docs/user_guide.md
requirements.txt

- Added Anthropic models config to the user guide
- Upgraded to neuro-san `0.5.32` to get a fix for Anthropic models

Document how to use Anthropic models

---

run.py

Nsflow cannot run multiple instances simultaneously because Neuro-San uses both a gRPC port and an HTTP port. However, in run.py, we only specify the gRPC port, so the HTTP port remains fixed and causes a conflict when another instance tries to use it.
- Add arg `server_http_port` of `run.py` and set the default to `8080`
- Add env var `NEURO_SAN_SERVER_HTTP_PORT`
- Change arg `server_port` to `server_grpc_port` and change default to `30011`
- Change env var `NEURO_SAN_SERVER_PORT` to `NEURO_SAN_SERVER_GRPC_PORT`

UN-3236 Modify run.py so that nsflow can run multiple instances at the same time

---

.env.example
docs/user_guide.md

- update env example for azure openai
- small changes on user guide on the same topic

Update env exmaple and user guide

---

.env.example
docs/user_guide.md

- Add gemini to `user_guide`
- Add gemini to `.env.example`

Add doc on gemini in user_guide and .env.example

---

requirements.txt

Upgrade neuro_san to 0.5.38

---

requirements.txt
run.py

Setting the thinking-file arg to the THINKING_FILE env variable if any, or `./logs` by default.

 #168 Use the logs dir in the root directory by default for the thinking file

---

docs/examples.md
docs/examples/agent_network_architect.md
docs/examples/agent_network_html_creator.md
registries/agent_network_architect.hocon
registries/agent_network_html_creator.hocon
registries/manifest.hocon

- Add md for `agent_network_architect` and `agent_network_html_creator`.
- Add some comments about `neuro-san` version and a few default values.
- Fix a few typos.

Add md fix typo for agent_network_architect and agent_network_html_generator

---

coded_tools/agent_network_architect/nsflow_selenium.py
coded_tools/agent_network_architect/send_gmail_hocon_html.py
coded_tools/agent_network_designer/get_agent_network_hocon.py
coded_tools/agent_network_html_generator.py
docs/examples/agent_network_architect.md
docs/examples/agent_network_html_creator.md
registries/agent_network_architect.hocon
registries/agent_network_designer.hocon

Add `agent_name` in `sly_data` as fallback

Add agent_name in sly data as fallback

---

.env.example
docs/user_guide.md

- Update `AzureOpenAI` documentation in `user_guide.md` and `.env.example`.

Update AzureOpenAI docs

---

README.md

- Add deepwiki badge or link for neuro-san and neuro-san-studios

Add deepwiki badge for neuro-san-studios

---

registries/banking_ops.hocon

Replaced repeated text in HOCON with variables referencing aaosa.hocon

Refactoring banking_ops.hocon 

---

registries/vc_repo_evaluator.hocon
registries/vibecoding_evaluator.hocon

Update vibe-coding model names

---

coded_tools/vc_repo_evaluator/manage_repo_eval.py
coded_tools/vibecoding_evaluator/manage_eval.py
registries/vc_repo_evaluator.hocon
registries/vibecoding_evaluator.hocon

Keep the variable names consistent between the two agent networks

Follow consistent variable naming

---

coded_tools/openai_code_interpreter.py
coded_tools/openai_tool.py
coded_tools/openai_web_search.py
registries/manifest.hocon
registries/openai_code_interpreter.hocon
registries/openai_web_search.hocon
toolbox/toolbox_info.hocon

- Add `web_search` and `code_interpreter` tools from OpenAI and also make them callable from toolbox.
- Add agent networks that call these tools
Documentation will be added in another PR.

OpenAI built-in tools

---

requirements-build.txt
tests/apps/gemini_api_key.py

`google-generativeai` has been deprecated and migrated to `google-genai`.

Change `requirements-build.txt` from `google-generativeai` to `google-genai` and modify the api in `gemini_api_key.py`

---

docs/examples.md
docs/examples/music_nerd_llm_fallbacks.md
docs/user_guide.md
registries/manifest.hocon
registries/music_nerd_llm_fallbacks.hocon

Updated the user guide to document how to configure LLM fallbacks.
Provided an example.

Document LLM fallbacks

---

coded_tools/arxiv_rag.py
coded_tools/base_rag.py
coded_tools/ddgs_search.py
coded_tools/docling_rag.py
coded_tools/google_serper.py
coded_tools/news_sentiment_analysis/sentiment_analysis.py
coded_tools/news_sentiment_analysis/web_scraping_technician.py
coded_tools/pdf_rag.py
coded_tools/wikipedia_rag.py
registries/coffee_finder.hocon

- Removed unnecessary commas in hocon style coffee_finder.hocon
- Applied `isort` and `black` changes that are done by running `make link`.

Code cleanup

---

requirements.txt
run.py

neuro-san==0.5.56
nsflow==0.5.19

Use latest nsflow and neuro-san

---

docs/user_guide.md

Updated the user guide with a section about external agent networks describing how to reference sub-networks

#300 Document how to use sub-networks, aka external agent networks
