cognizant-ai-lab/neuro-san-studio

run.py

Added a `--no-html` option to `run.py` to skip `generate_html_files` when running the demos.
Reasons to skip the generation of html files:
- we know they haven't changed
- we don't look at them
- we're using another client that doesn't use them
Also removed the --demo-mode flag because the demos live in this repo now.

Option to skip html file generation in run.py for faster start time

---

coded_tools/airline_policy/extract_docs.py
requirements.txt

- Modify import statement in `coded_tools/airline_policy/extract_docs.py` from `PyPDF2` to `pypdf`
- Remove pypdf2 in `requirements.txt`
- Run `ExtractDocs.extract_pdf_content` with pypdf and pypdf2.

Remove pypdf2

---

requirements.txt

In order to get the CORS fix to neuro-san-demos, we had to update dependencies for both neuro-san and the web client. This PR accomplishes that goal.

Use latest web client and neuro-san to get CORS updates

---

coded_tools/music_nerd_pro/accounting.py
coded_tools/music_nerd_pro_local/accounting.py
coded_tools/music_nerd_pro_sly/accounting.py
coded_tools/music_nerd_pro_sly_local/accounting.py
requirements.txt

Upgraded:
- neuro-san to 0.5.22
- neuro-san-web-client to 0.1.10
And made the Music Nerd cost calculation less easy for LLMs to guess without calling the tool.

Upgrade neuro-san and neuro-san-web-client

---

Makefile
README.md
requirements.txt
run.py

Changes:
- Use `nsflow` as the default client in `neuro-san-demos`
- Add option to use `flask-web-client`
- Add option to run neuro-san-demos in `client-only` and `server-only` mode
- Add env variable `AGENT_MANIFEST_UPDATE_PERIOD_SECONDS` that updates the manifest at a given interval
- Update makefile to work with any python `VIRTUAL_ENV`
- Reorder sections in `README.md`

Use nsflow client as default

---

docs/user_guide.md
registries/manifest.hocon
registries/smart_home_include.hocon

- Add smart_home_include.hocon and turn it on in manifest
- Point to the above hocon as example in user_guide.md

Add smart_home_include.hocon as an example to how to import hocon file

---

deploy/Dockerfile
deploy/build.sh
deploy/logging.json

We were deploying the demos that were coming with the `neuro-san` library. Now that we've consolidated them into `neuro-san-demo` we need to deploy the `neuro-san-demos` one instead.

Deploy neuro-san-demos agent networks instead of those from neuro-san

---

.github/workflows/build-push.yml

This PR brings our common workflow from neuro-ai to the neuro-san-demos repo. Specifically, that is:
A merge to main will trigger a docker image build and that image is pushed to our ECR. Then that image is deployed to the dev environment.
Similarly, a github Release of neuro-san-demos will trigger an image build and then deploy that image to the staging environment.
The production deployment case is still handled manually.
Also note, this PR updates the deployed version of the neuro-san-demos image, it does not update the deployed ui version. The ui version is from a custom ui build that is still handled manually.

Add action to build and push docker image

---

.github/workflows/build-push.yml

This PR fixes a sure-to-be-common typo cognizant-ai-labs instead of the correct cognizant-ai-lab.

Correct typo in new org name

---

docs/user_guide.md

- Add toolbox section in user_guide with the following topics:
- Default tools in toolbox
- Usage in agent network config
- Adding tools in toolbox
- Add a topic about using `args` keys in `Advanced` section

Add toolbox section in user_guide

---

docs/examples.md
docs/examples/log_analyzer.md

Refactored `docs/examples.md` to:
- organize the examples by type
- put tags on each example to quickly identify what they showcase

Organize examples in examples.md 

---

docs/tutorial.md
docs/user_guide.md

This file moved in a recent refactoring.

Fix links to toolbox_info.hocon in neuro-san repo

---

registries/agentic_rag.hocon

To use tool from toolbox, the key is changed from `basetool` to `toolbox`.

Update key in agentic rag from basetool to toolbox

---

requirements.txt

Pull in latest neuro-san to avoid http server start-up failure.

Use latest neuro-san to fix server start-up issue

---

coded_tools/agent_network_architect/send_gmail_hocon_html.py

Previously, the fallback to sly_data was only triggered if both attachment paths were invalid. This caused issues in cases where only one of the two required files (HOCON or HTML) was present — the fallback logic was skipped even though the attachments were incomplete.
This change updates the condition to ensure the fallback is triggered whenever there are no valid attachments at all.

Fix bug for email sending tool for agent_network_architect

---

registries/conscious_agent.hocon
registries/kwik_agents.hocon

- `gpt-4.1-2025-04-14` or `gpt-4.1` is currently in the default llm info file and can be used by "model_name"
- `use_model_name` is not a valid key for llm_config. Only use it in llm info file for aliasing. For example
"gpt-4.1": {
"use_model_name": "gpt-4.1-2025-04-14"
}
This will points to `gpt-4.1-2025-04-14` when "model_name" in `llm_config` is `gpt-4.1`.
- For models and providers extension in agent network
- Default provider, new model:
```hocon
"llm_config": {
"class": "openai",
"model_name": "gpt-4.1-mini",
}
```
- New provider:
```hocon
"llm_config": {
"class": "langchain_groq.chat_models.ChatGroq",
}
```

remove class and use_model_name in llm_config

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/tests.yml
README.md
deploy/Dockerfile
requirements.txt

In order to support python 3.13:
- updated neuro-san to the latest version, that removes the requirement for an old protobuf dependency
- updated the Docker images to use python 3.13
- update the doc where needed

Upgrade to neuro-san 0.5.49 for compatibility with python 3.13

---

coded_tools/website_search/website_search.py

The library name was changed from `duckduckgo_search` to `ddgs`.

change duckduckgo_search to ddgs

---

requirements.txt

This will get the AGENT_TOOL_RESULT messages flowing back into the stream with essential caller/callee origin information that disappeared with neuro-san==0.5.48

Update to neuro-san==0.5.51

---

registries/coffee_finder_advanced.hocon

A single line fix works better for now.
Context:
When a users asks question like this, the agent places multiple orders, which is not expected.
> **Human:**  
>  
> My name is John Arthur  
> Get me the best coffee this evening
> 
> 
> **AI:**  
>  
> Your order for the best coffee has been successfully placed at:  
>  
> 1. **Bob's Coffee Shop** – Order ID: 101, Order Details: best coffee  
> 2. **Joe's Gas Station** – Order ID: 301, Order Details: best coffee  
>  
> *Henry's Fast Food* can also fulfill your order—if you'd like to proceed with them or have specific preferences, please let me know!

Coffee Finder Advanced: fix for duplicate orders of the same item

---

requirements.txt

Upgrading to neuro-san==0.5.60 to get:
* @Noravee 's new token accounting 
* Start of intra-agent JSON <-> refactoring (more will come later)
* metadata in Connectivity() responses
* large message line ingestion for clients
* logging fidelity fixes
* lazy LLM provider imports
W/rt the last one we also need to pull in langchain-anthropic here so that pylint is happy.
See question below about how much we really want to import here.

Upgrade to neuro-san==0.5.60

---

coded_tools/a2a_research_report/a2a_research_report.py
docs/examples/a2a_research_report.md
registries/a2a_research_report.hocon
registries/manifest.hocon
servers/a2a/README.md
servers/a2a/agent_executor.py
servers/a2a/server.py

The A2A protocol is still under development. Since this example was created, the **A2A Python SDK** has changed, and the current code will not run correctly with the latest version of A2A.  
To address this:  
- Update both the **A2A client** and **A2A server** so the example can run successfully.  
- Revise the setup instructions, as A2A is now available on PyPI (previously it was not).  
- Add a README file in the `servers/a2a` folder with usage and configuration details.

UN-3528: Update a2a example

---

README.md
requirements.txt
run.py

Made neuro-san-web-client optional:
- Removed it from `requirement.txt`
- Added a check and message in `run.py`
- Simplified `README.md` with a single way to run neuro-san-studio
- Added community projects + links to the `README.md`

Remove neuro-san-web-client from requirements.txt
